/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 maxwell_dance.glb --transform
Author: sashanedurak (https://sketchfab.com/sashanedurak)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maxwell-dance-801b4ae7347a40fc849d395a38b01776
Title: Maxwell Dance
*/
import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, PositionalAudio } from "@react-three/drei";

export function Maxwell(props, { ready }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/maxwell_dance-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  console.log(animations);
  useEffect(() => {
    actions.dingusAction.play();
  }, [actions]);

  return (
    <group scale={0.1} ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group>
              {ready && (
                <PositionalAudio
                  autoplay
                  loop
                  url="/maxwell.mp3"
                  distance={1}
                />
              )}
            </group>
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="dingus_2">
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.dingus}
                />
                <mesh
                  name="Object_5"
                  geometry={nodes.Object_5.geometry}
                  material={materials.whiskers}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/maxwell_dance-transformed.glb");
